name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - uses: actions/checkout@v2
      - run: make install-dev-dependencies-linux
      - run: make test
      - run: goveralls -coverprofile=coverage.out -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
